# Generated by Django 5.2 on 2025-04-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_products_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
